language: python
python:
- 3.6
dist: trusty
install:
- pip install -r requirements.txt
script:
- mkdir -p ~/.config/hca
- export HCA_CONFIG_FILE=~/.config/hca/config.${TRAVIS_BRANCH}.json
- make test
branches:
  only:
  - dev
  - integration
notifications:
  slack:
    secure: CSLf58bI+VjF9FS7/eHt2S6y7/ema6h9kUSX9ykCdEt8Ut1G1t4OS334lkhb37dCNq1iPOLauXdANi/+kf5wQ+34eK0yM5pq1f2InekoYGjvPYU2WLXsmbdBBgAWoX/yDmlEZ8WtdKNhVGFycSKfDQrF2HZlhJHZ4w8yIIBgsySXb5lczwcPj6Ky62XcArgJnq4CtZkTIxpolKcZxHPHcwc/w1SwtD+l+lNGUwLWh1ftCJQOC2LLcfzx67ujkbWxh2ys8OGkQs+AuOCKHMLnFJcWQkGxKUAd+c3j9fSnPAhDh6OnHGbrMx7+RqgB8ZQna9BYuJCDJLq9kwCaJhFavAPhEmFSFpSMK44JEFOkUalayNyn97VvR63ORI5AwmThSaO9Su70qWLv6OEck0YNyPUqwTVatLf54npKivFVPpucdkfMEgqDQHRmXTiILkXTs6mHwj55Xeyu/+t+fYDnOxbrohdlz7muLACDpIskclq7smyLEvxPOEb7HQl0x4w2sJF80unEuZwKEeWBtSz6XlBvSzhCgIU+wxvnGcMerJol7CunpmbPz0yZdp3KP1DL6B4GRfZHjwI9UiMl0vI0Jtw1jpe0jemili9JaTC7KGeefQeZJTsOoEoz9FNLcIDfDmgkeR8r6OnjYt5Gmygb8jHV1SALHXm2KGaw3iA5z68=
